### ISSUE TITLE
design suggestion 

### ISSUE THREAD

**Issue by juarseve** [sohanuzzamansoad/BankingSystem#3]
Hello! I suggest to follow decorator design pattern on Bank package instead of using simple inheritance. Thus improving code extensibility and maintainability if necessary.

![image](https://github.com/ssoad/BankingSystem/assets/136662753/2ef33f4b-c133-43a5-9448-ee7e31e72b48)

**Comment by ssoad** [comment]
Thanks for your suggestion. You can fork and make a great contribution on it. You're welcome for any type of contribution.
