### ISSUE TITLE
design suggestion

### ISSUE THREAD

**Issue by juarseve** [sohanuzzamansoad/BankingSystem#4]
Hello! You could use composite design pattern if you wish to create more complex BankAccount objects and treat them all in the same way. Here's a reference class diagram.

![image](https://github.com/ssoad/BankingSystem/assets/136662753/986fe068-4785-4e8a-9121-3d2456ac378a)

**Comment by ssoad** [comment]
Thanks for creating the issue.This repository is now open for contribution. So, you can work on it. @juarseve
